name: Build
on: [push, pull_request]

jobs:
    build:
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}

        strategy:
            fail-fast: false
            matrix:
                config:
                - {
                    name: "Windows MSVC",
                    os: windows-latest
                  }
                - {
                    name: "Ubuntu GCC",
                    os: ubuntu-latest
                  }
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install
              run: sudo apt-get install mesa-common-dev libglu1-mesa-dev
              if: ${{ matrix.config.os == 'ubuntu-latest' }}

            - name: Build Extern
              shell: bash
              run: |
                  if [ "$RUNNER_OS" == "Windows" ]; then
                      cmd.exe //c build-extern.cmd
                  elif [ "$RUNNER_OS" == "Linux" ]; then
                      ./build-extern.sh
                  fi

            - name: Build
              shell: bash
              run: |
                  mkdir build
                  cd build
                  cmake ..
                  cmake --build .
